name: 'React Compiler Healthcheck'
description: 'Verify React components are optimized by React Compiler'
author: 'Simeon Grancharov'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  include:
    description: 'Glob patterns for files to check (comma-separated)'
    required: false
    default: '**/*.jsx,**/*.tsx'
  exclude:
    description: 'Glob patterns to exclude (comma-separated)'
    required: false
    default: '**/node_modules/**,**/*.test.{js,jsx,ts,tsx},**/*.spec.{js,jsx,ts,tsx},**/__tests__/**'
  fail-on-error:
    description: 'Fail the action if any component fails compilation'
    required: false
    default: 'true'
  fail-threshold:
    description: 'Fail if error percentage exceeds this value (0-100). Ignored if fail-on-error is true.'
    required: false
    default: '0'
  comment-on-pr:
    description: 'Post results as a PR comment'
    required: false
    default: 'true'
  annotations:
    description: 'Add inline annotations to PR'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for the action'
    required: false
    default: '.'
  github-token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}

outputs:
  total-files:
    description: 'Total files scanned'
  total-components:
    description: 'Total components analyzed'
  passed:
    description: 'Components successfully compiled'
  failed:
    description: 'Components that failed compilation'
  pass-rate:
    description: 'Percentage of components that passed'
  success:
    description: 'Whether the healthcheck passed'

runs:
  using: 'node20'
  main: 'dist/action.js'
