import type { HealthcheckResult, FileCheckResult, LoggerEvent } from "../core/types";

export type MarkdownReportOptions = {
  repoUrl?: string;
  commitSha?: string;
  showSuccesses?: boolean;
};

export function formatMarkdownReport(
  result: HealthcheckResult,
  options: MarkdownReportOptions = {}
): string {
  const { repoUrl, commitSha, showSuccesses = false } = options;
  const { summary, results } = result;
  const lines: string[] = [];

  const passRate = summary.totalComponents > 0
    ? ((summary.passedComponents / summary.totalComponents) * 100).toFixed(1)
    : "0.0";

  const statusEmoji = summary.failedComponents === 0 ? "✅" : "❌";

  lines.push(`## ${statusEmoji} React Compiler Healthcheck`);
  lines.push("");

  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(`| Files scanned | ${summary.totalFiles} |`);
  lines.push(`| Total components | ${summary.totalComponents} |`);
  lines.push(`| Passed | ${summary.passedComponents} |`);
  lines.push(`| Failed | ${summary.failedComponents} |`);
  lines.push(`| Pass rate | ${passRate}% |`);
  lines.push("");

  const failedFiles = results.filter(
    r => r.compilationResult.failedCompilations.length > 0 || r.error
  );

  if (failedFiles.length > 0) {
    lines.push("<details>");
    lines.push(`<summary>❌ Failed Components (${summary.failedComponents})</summary>`);
    lines.push("");

    for (const file of failedFiles) {
      if (file.error) {
        lines.push(`#### \`${file.filePath}\``);
        lines.push(`> ⚠️ ${file.error}`);
        lines.push("");
        continue;
      }

      for (const failure of file.compilationResult.failedCompilations) {
        const line = failure.fnLoc?.start?.line ?? 0;
        const name = failure.fnName ?? "anonymous";
        const reason = failure.detail?.reason ?? failure.detail?.description ?? "Unknown reason";

        const fileLink = formatFileLink(file.filePath, line, repoUrl, commitSha);
        lines.push(`#### ${fileLink} - \`${name}\``);
        lines.push(`> ${reason}`);

        if (failure.detail?.suggestions?.length) {
          lines.push("");
          lines.push("**Suggestions:**");
          for (const suggestion of failure.detail.suggestions) {
            lines.push(`- ${suggestion}`);
          }
        }
        lines.push("");
      }
    }

    lines.push("</details>");
    lines.push("");
  }

  if (showSuccesses && summary.passedComponents > 0) {
    const successfulFiles = results.filter(
      r => r.compilationResult.successfulCompilations.length > 0
    );

    lines.push("<details>");
    lines.push(`<summary>✅ Optimized Components (${summary.passedComponents})</summary>`);
    lines.push("");

    for (const file of successfulFiles) {
      for (const success of file.compilationResult.successfulCompilations) {
        const line = success.fnLoc?.start?.line ?? 0;
        const name = success.fnName ?? "anonymous";
        const fileLink = formatFileLink(file.filePath, line, repoUrl, commitSha);
        lines.push(`- ${fileLink} - \`${name}\``);
      }
    }

    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  if (summary.failedComponents === 0 && summary.totalComponents > 0) {
    lines.push("🎉 **All components are optimized by React Compiler!**");
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by [React Compiler Healthcheck](https://github.com/anthropics/react-compiler-healthcheck)*");

  return lines.join("\n");
}

function formatFileLink(
  filePath: string,
  line: number,
  repoUrl?: string,
  commitSha?: string
): string {
  if (repoUrl && commitSha) {
    const url = `${repoUrl}/blob/${commitSha}/${filePath}#L${line}`;
    return `[\`${filePath}:${line}\`](${url})`;
  }
  return `\`${filePath}:${line}\``;
}
